### ISSUE TITLE
Rendering issue and scrollbar

### ISSUE THREAD

**Issue by nazrhyn** [dvcrn/markright#21]
###### This is for the Windows 64-bit installer version at **0.33.6**.
![image](https://cloud.githubusercontent.com/assets/1672405/11065646/90717c08-8792-11e5-8e9b-ebf2a85ff402.png)

#### Rendering Issue
The following Markdown...

```
1. A list
2. More list

* First level
  * Second level
```

...which renders as the following, on GitHub...

1. A list
2. More list

* First level
  * Second level

...is rendering as in the screenshot, above, in MarkRight.

#### Scrollbar
There's a funny floating scrollbar showing in the screenshot, above.

#### Markdown
I've put the text of my Markdown test document into a gist, here:
https://gist.github.com/nazrhyn/40683f37ff3298f95ebd

**Comment by dvcrn** [comment]
List bug ref - https://github.com/chjj/marked/issues/530.

**Comment by nazrhyn** [comment]
Ah, thank you for finding that issue.

I can make a separate issue for the scrollbar thing, if you'd like? I probably shouldn't've combined them; I know better.

**Comment by dvcrn** [comment]
Looks like the scrollbar thing is caused by the `max-width` property here https://github.com/dvcrn/markright/blob/master/node/ui/css/main.css#L40

There was a reason why I put that in in the first place but I just can't remember why. I'll take it out. 

For the list bug, it seems like marked is kind of inactive. We should think about switching to a alternative - https://github.com/dvcrn/markright/issues/24
